### ISSUE TITLE
new release, conda build, and docs

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/mdentropy#36]
I think this package is ready for `v0.5`

**Comment by cing** [comment]
Was hoping to cite mdentropy in a new paper, submitting final revisions in the next couple of weeks. Just for some basic mutinf calculations. I'm currently citing the mdentropy 0.2 zenodo, but a 0.5 release would also be nice to cite! 

P.S. has there been any major bug fixes committed since 0.2 (using grassberger with default scripts)?

**Comment by cxhernandez** [comment]
> Was hoping to cite mdentropy in a new paper, submitting final revisions in the next couple of weeks. Just for some basic mutinf calculations. I'm currently citing the mdentropy 0.2 zenodo, but a 0.5 release would also be nice to cite!

Awesome! Let me know when it comes out 😄 

> P.S. has there been any major bug fixes committed since 0.2 (using grassberger with default scripts)?

Besides the grassberger change, I don't believe there's been any major changes to the mutual information code, just some [reorganization/name changes](https://github.com/msmbuilder/mdentropy/commit/aa649b8b5d8a71edb0c8c0b518e7cbb9c4eb6086) in the API (e.g. `mi` is now `mutinf` for clarity).

**Comment by cxhernandez** [comment]
done in #46
