### ISSUE TITLE
Normalized mutual information seems not normalized

### ISSUE THREAD

**Issue by xiaoj12** [msmbuilder/mdentropy#58]
Hi, 

I'm trying to use mdentropy 0.3.0.dev0 to compute the mutual information shared among dihedral angles in an MD trajectory.  I was expecting the the "normed = True" option in the DihedralMutualInformation (code attached below) would return the normalized mutual information.
```
dmutinf = DihedralMutualInformation(n_bins=3, method='knn', normed=True,types=['phi', 'psi','chi1','chi2','chi3','chi4'])
M_Dihedral_norm = dmutinf.partial_transform(traj)
```
However, the maximum value in the returned array is as large as 363.3 instead of 1 in the diagonal direction. Moreover, when I specified "normed = False", the maximum value in the return mutual information became a smaller number of 4.37. 

Any clue what happened? Are these results reasonable? Actually, I may have a guess according to my understanding of mutual information though I'm not sure if that's right or not. Notice that the returned array of the mutual information has the shape of (n_residues, n_residues). I could imagine the mutual information computed for a pair of residues was averaged from the mutual information shared among each dihedral angle within this pair of residues, which may lead to a non-1 normalized mutual information shared by the residue with itself. But when I checked the codes of mdentropy, I couldn't find any process like what I guess above. Thus, one more question is could you explain how you compute the mutual information for a pair of residues with features of multiple dihedral angles.

Thanks!

JJ

**Comment by cxhernandez** [comment]
Thanks for the report @xiaoj12! I'm fairly certain this problem is related to #51. My best guess at the moment is that there's a constant correction missing from `knn_entropy`, which causes it to underestimate the empirical entropy (note that this correction should cancel out when calculating MI, so that's unaffected). If you're truly interested, we can discuss more about what this correction should be.

Although there are many ways to normalize MI (`nmi`), the approach I took was `nmi = mi / sqrt(ent_x * ent_y)`. If either of the entropies are underestimated, then there's a chance you'll get either inflated or negative values for `nmi`. My recommendation in the meantime is to not use normalized mutual information scores. Recently, I've been grappling with the concept of what a normalized mutual information score really means physically, as mutual information already is in units of bits and makes it more useful for comparison.

As for how multiply dihedrals are accounted for, MI for each dihedral/feature is just summed up per residue (as a rough approximation since truly calculating the joint MI is rather expensive). The rational for this over just averaging the values is that different residues can have different numbers of dihedrals, and it makes physical sense to give more weight to residues with more observables (e.g. arginines are probably more important than glycine or alanine).

**Comment by xiaoj12** [comment]
@cxhernandez  Thanks for your fast reply. What you mentioned in #51 is really interesting. I didn't realize there were such profound differences in the entropy calculation in the discrete and continuous cases. 

I did some quick tests using the data I have. Similar to #51, I do see the nmi from knn estimator is different from the one from naive,  chaowangjost and grassberger (they return the nmi in the range of [0,1] while knn inflates again). However, I can also see all these estimators result in very closed inflated nmi matrices for some other data set. This might be due to the underestimated entropy as you said, though I'm not sure why some of entropy was underestimated yet.  Thus, I may be questioning whether it is a constant difference or not.

I considered nmi instead of the mi as I wanted to compare how differently the residues could correlate with each other. Like correlation vs. covarriance, the scalable/normalized variable seems more proper to me at the beginning. But now I agree the MI has more physically meanings than the nmi. 

As to MI, what estimator would you recommend? (my trajectory originally contains about 300 residues and 500,000 frames, I have to stride it by a factor of 10.)

**Comment by cxhernandez** [comment]
> As to MI, what estimator would you recommend? 

KNN seems to be the most accurate and is what's implemented in `sklearn`.
