### ISSUE TITLE
Default bin size and change bin size for mdentropy.metrics.AlphaAngleMutualInformation

### ISSUE THREAD

**Issue by ragarwa4** [msmbuilder/mdentropy#66]
What is the default value for bin size when using AlphaAngleMutualInformation and how can I change the bin size?

Also how to use Binning Functions?

Thanks

**Comment by cxhernandez** [comment]
> What is the default value for bin size when using AlphaAngleMutualInformation and how can I change the bin size?

By default, the latest version of the code actually uses a k-nearest neighbors approach to estimating the mutual information as described by [Kraskov, et al.](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.69.066138) So there shouldn't be a need to change `n_bins`.

> Also how to use Binning Functions?

You can refer to the [docs](http://msmbuilder.org/mdentropy/0.3.0/api.html#binning-functions) for the specific function you're interested in, but work by specifying `n_bins` as the number of bins, specifying `rng` as a list of min/max tuples to consider binning over for each variable, and then, finally, an arbitrary number of variables to bin over. So if I had a single variable `x` that I want 5 bins over `(0, 10)` it'd look something like:

```python
from mdentropy.core.binning import hist

bins = hist(5, [(0, 1)], x)
```

But this is all done under the hood if you're using the estimators, such as `AlphaAngleMutualInformation`, and I would recommend using [scitkit-learn](http://scikit-learn.org/stable/modules/density.html) for these sorts of calculations otherwise.
